server:
  port: 9022
spring:
  application:
    name: product
  datasource:
      url: jdbc:mysql://localhost:3306/svsp_customer?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      druid:
        driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  #    password: 123456
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:1



logging:
  level:
    com.jalja.org.spring.simple.dao.FeignUserClient: DEBUG
    org.springframework.cloud.openfeign: debug
#mapper:
#  mappers:
#     com.microservice.skeleton.upms.mapper
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 6
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 18
  client:
      service-url:
        defaultZone: http://127.0.0.1:9010/eureka/
