spring:
  zipkin:
    base-url: http://localhost:9411


#需要权限控制的url
auth-props:
  testurl: abcdedf
  urls:
    - /customer/api
    - /product/api



#zuul:
#  ignored-patterns: /**/v2/api-docs,/**/swagger-resources/**,/**/configuration/ui,/**/configuration/security
#    ,/**/swagger-ui.html,/**/swagger-resources/configuration/ui,/**/doc.html,/**/webjars/**


